<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Offramp.Ide.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Offramp.Ide\Offramp.Ide.csproj" />
    <ProjectReference Include="..\Offramp.Fixtures\Offramp.Fixtures.csproj" />
  </ItemGroup>
</Project>
