<Project Sdk="Microsoft.NET.Sdk">
  <!-- Not in the solution, but under the root Directory.Packages.props (OFR1301). -->
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
  </ItemGroup>
</Project>
