using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Offramp.Scaffolding.Text;

/// <summary>Spelling C# in generated files: qualified type names, identifiers, and the file header.</summary>
public static class CSharpText
{
    /// <summary>Fully qualified, with keywords for special types (<c>string</c>, <c>int?</c>): valid in any namespace without usings.</summary>
    private static readonly SymbolDisplayFormat QualifiedFormat = SymbolDisplayFormat.CSharpErrorMessageFormat
        .WithMiscellaneousOptions(SymbolDisplayFormat.CSharpErrorMessageFormat.MiscellaneousOptions | SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    public static string Type(ITypeSymbol type) => type.ToDisplayString(QualifiedFormat);

    /// <summary>An identifier, escaped with <c>@</c> when it is a keyword.</summary>
    public static string Identifier(string name) =>
        SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None ? "@" + name : name;

    /// <summary><c>samAccountName</c> → <c>SamAccountName</c>.</summary>
    public static string Pascal(string name) => name.Length == 0 ? name : char.ToUpperInvariant(name[0]) + name[1..];

    /// <summary><c>IDirectoryLookup</c> → <c>DirectoryLookup</c>; names without the I prefix stay.</summary>
    public static string Stem(string interfaceName) =>
        interfaceName.Length > 1 && interfaceName[0] == 'I' && char.IsUpper(interfaceName[1]) ? interfaceName[1..] : interfaceName;

    /// <summary><c>Accounts.Windows.Host</c> → <c>accounts-windows-host</c>.</summary>
    public static string Kebab(string name)
    {
        var text = new StringBuilder();
        foreach (var c in name)
        {
            text.Append(char.IsLetterOrDigit(c) ? char.ToLowerInvariant(c) : '-');
        }

        return text.ToString().Trim('-');
    }

    /// <summary>The first line of every generated C# file: marks it generated, so analyzers and nullable warnings leave it alone.</summary>
    public const string Header = "// <auto-generated>Generated by offramp remote. Regenerate instead of editing, or delete this header to take ownership.</auto-generated>";
}
