using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Offramp.Scaffolding.Text;

namespace Offramp.Scaffolding.Remote;

/// <summary>
/// The client project: a class implementing the interface over HTTP (typed <c>HttpClient</c>),
/// the optional asynchronous interface, the JSON call helper for the chosen serializer, and the
/// DI registration with the local/remote switch.
/// </summary>
internal static class ClientTemplate
{
    public static IEnumerable<(string Path, string Text)> Files(
        RemoteLayout layout, IReadOnlyList<BoundaryMember> members, WireTypes wire, IReadOnlyList<string> targetFrameworks, string serializer, bool asyncVariant)
    {
        var directory = layout.ClientDirectory;
        yield return (layout.ClientProject, Project(layout, targetFrameworks, serializer));
        yield return ($"{directory}/Remote{layout.Stem}.cs", Client(layout, members, wire, asyncVariant));
        if (asyncVariant)
        {
            yield return ($"{directory}/{layout.InterfaceName}Async.cs", AsyncInterface(layout, members));
        }

        yield return ($"{directory}/{layout.Stem}Mapping.cs", MappingTemplate.Text(layout, wire, layout.ClientNamespace));
        yield return ($"{directory}/RemoteCall.cs", serializer == "newtonsoft" ? NewtonsoftCall(layout) : SystemTextJsonCall(layout));
        yield return ($"{directory}/{layout.Stem}Registration.cs", Registration(layout, asyncVariant));
    }

    /// <summary>The DI switch as the application calls it.</summary>
    public static string RegistrationCall(RemoteLayout layout)
    {
        var local = layout.Implementation.InstanceConstructors.Any(c => c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public)
            ? $"new {layout.ImplementationFullName}()"
            : $"Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<{layout.ImplementationFullName}>(provider)";
        return $"services.Add{layout.Stem}(configuration, provider => {local});";
    }

    private static string Project(RemoteLayout layout, IReadOnlyList<string> targetFrameworks, string serializer)
    {
        var frameworks = targetFrameworks.Count == 1
            ? $"<TargetFramework>{targetFrameworks[0]}</TargetFramework>"
            : $"<TargetFrameworks>{string.Join(";", targetFrameworks)}</TargetFrameworks>";
        var json = serializer == "newtonsoft"
            ? $"    <PackageReference Include=\"Newtonsoft.Json\" Version=\"{ScaffoldPackages.Version("Newtonsoft.Json")}\" />\n"
            : "";
        var framework = serializer == "newtonsoft"
            ? ""
            : $"    <PackageReference Include=\"System.Text.Json\" Version=\"{ScaffoldPackages.Version("System.Text.Json")}\" />\n";
        return $$"""
            <Project Sdk="Microsoft.NET.Sdk">
              <!-- Generated by offramp remote: {{layout.InterfaceFullName}} over HTTP, for the projects that call it. -->
              <PropertyGroup>
                {{frameworks}}
                <LangVersion>latest</LangVersion>
                <Nullable>disable</Nullable>
                <ImplicitUsings>disable</ImplicitUsings>
                <RootNamespace>{{layout.ClientNamespace}}</RootNamespace>
            {{HostTemplate.CentralPackages(layout)}}  </PropertyGroup>

              <ItemGroup>
                <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="{{ScaffoldPackages.Version("Microsoft.Extensions.Configuration.Abstractions")}}" />
                <PackageReference Include="Microsoft.Extensions.Http" Version="{{ScaffoldPackages.Version("Microsoft.Extensions.Http")}}" />
            {{json}}  </ItemGroup>

              <!-- .NET Framework needs HttpClient referenced{{(framework.Length > 0 ? " and System.Text.Json from NuGet" : "")}}; modern .NET has them. -->
              <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">
                <Reference Include="System.Net.Http" />
            {{framework}}  </ItemGroup>

              <ItemGroup>
                <ProjectReference Include="{{RemoteLayout.Relative(layout.ClientDirectory, layout.ProjectFile)}}" />
                <ProjectReference Include="{{RemoteLayout.Relative(layout.ClientDirectory, layout.ContractsProject)}}" />
              </ItemGroup>
            </Project>

            """;
    }

    private static string Client(RemoteLayout layout, IReadOnlyList<BoundaryMember> members, WireTypes wire, bool asyncVariant)
    {
        var body = new StringBuilder();
        foreach (var member in members.Where(m => m.Method is not null || m.Status != "remote"))
        {
            body.Append('\n');
            if (member.Status != "remote")
            {
                body.Append(Unsupported(member));
                continue;
            }

            var method = member.Method!;
            var parameters = string.Join(", ", method.Parameters.Select(Parameter));
            var returns = CSharpText.Type(method.ReturnType);
            var token = member.Arguments.FirstOrDefault(a => a.Property is null)?.Parameter.Name;
            if (!member.Async)
            {
                var forward = string.Join(", ", method.Parameters.Select(p => CSharpText.Identifier(p.Name)).Append("CancellationToken.None"));
                body.Append(CultureInfo.InvariantCulture, $"        /// <remarks>Blocks until the host answers (OFR4020); <see cref=\"{member.AsyncName}\"/> does not.</remarks>\n");
                body.Append(CultureInfo.InvariantCulture, $"        public {returns} {CSharpText.Identifier(method.Name)}({parameters})\n        {{\n");
                body.Append(method.ReturnsVoid
                    ? $"            {member.AsyncName}({forward}).ConfigureAwait(false).GetAwaiter().GetResult();\n"
                    : $"            return {member.AsyncName}({forward}).ConfigureAwait(false).GetAwaiter().GetResult();\n");
                body.Append("        }\n\n");
            }

            var asyncReturns = member.Async ? returns : member.Returns is { } r ? $"Task<{CSharpText.Type(r)}>" : "Task";
            var asyncParameters = member.Async ? parameters : string.Join(", ", method.Parameters.Select(Parameter).Append("CancellationToken cancellationToken = default(CancellationToken)"));
            var visibility = member.Async || asyncVariant ? "public" : "private";
            body.Append(CultureInfo.InvariantCulture, $"        {visibility} async {asyncReturns} {member.AsyncName}({asyncParameters})\n        {{\n");
            body.Append(CultureInfo.InvariantCulture, $"            var request = new {layout.Request(member)}");
            var assignments = member.Arguments.Where(a => a.Property is not null).Select(a => $"{a.Property} = {wire.ToWire(a.Parameter.Type, CSharpText.Identifier(a.Parameter.Name))}").ToList();
            body.Append(assignments.Count == 0 ? "();\n" : " { " + string.Join(", ", assignments) + " };\n");
            var cancellation = member.Async ? token is null ? "CancellationToken.None" : CSharpText.Identifier(token) : "cancellationToken";
            if (member.Returns is { } value)
            {
                body.Append(CultureInfo.InvariantCulture, $"            var response = await RemoteCall.PostAsync<{layout.Request(member)}, {wire.WireType(value)}>(_http, {layout.Routes}.{member.Key}, request, {cancellation}).ConfigureAwait(false);\n");
                body.Append(CultureInfo.InvariantCulture, $"            return {wire.FromWire(value, "response")};\n");
            }
            else
            {
                body.Append(CultureInfo.InvariantCulture, $"            await RemoteCall.PostAsync(_http, {layout.Routes}.{member.Key}, request, {cancellation}).ConfigureAwait(false);\n");
            }

            body.Append("        }\n");
        }

        var interfaces = layout.InterfaceFullName + (asyncVariant ? ", " + layout.InterfaceName + "Async" : "");
        return $$"""
            {{CSharpText.Header}}
            namespace {{layout.ClientNamespace}}
            {
                using System;
                using System.Net.Http;
                using System.Threading;
                using System.Threading.Tasks;

                /// <summary><c>{{layout.InterfaceFullName}}</c> over HTTP: every call is a POST to the Windows host.</summary>
                public sealed class Remote{{layout.Stem}} : {{interfaces}}
                {
                    private readonly HttpClient _http;

                    /// <param name="http">A client whose base address is the host's (registered by <see cref="{{layout.Stem}}Registration"/>).</param>
                    public Remote{{layout.Stem}}(HttpClient http)
                    {
                        _http = http ?? throw new ArgumentNullException(nameof(http));
                    }
            {{body}}    }
            }

            """;
    }

    private static string Unsupported(BoundaryMember member)
    {
        var why = $"{member.Symbol.Name} does not cross the remote boundary (offramp remote --skip-member {member.Symbol.Name}).";
        return member.Symbol switch
        {
            IMethodSymbol method => $"        public {CSharpText.Type(method.ReturnType)} {CSharpText.Identifier(method.Name)}({string.Join(", ", method.Parameters.Select(Parameter))})\n        {{\n            throw new NotSupportedException(\"{why}\");\n        }}\n",
            IPropertySymbol property => $"        public {CSharpText.Type(property.Type)} {CSharpText.Identifier(property.Name)}\n        {{\n"
                + (property.GetMethod is not null ? $"            get {{ throw new NotSupportedException(\"{why}\"); }}\n" : "")
                + (property.SetMethod is not null ? $"            set {{ throw new NotSupportedException(\"{why}\"); }}\n" : "")
                + "        }\n",
            IEventSymbol @event => $"        public event {CSharpText.Type(@event.Type)} {CSharpText.Identifier(@event.Name)}\n        {{\n            add {{ throw new NotSupportedException(\"{why}\"); }}\n            remove {{ throw new NotSupportedException(\"{why}\"); }}\n        }}\n",
            _ => "",
        };
    }

    private static string AsyncInterface(RemoteLayout layout, IReadOnlyList<BoundaryMember> members)
    {
        var body = new StringBuilder();
        foreach (var member in members.Where(m => m.Status == "remote" && !m.Async))
        {
            var method = member.Method!;
            var returns = member.Returns is { } r ? $"Task<{CSharpText.Type(r)}>" : "Task";
            var parameters = string.Join(", ", method.Parameters.Select(Parameter).Append("CancellationToken cancellationToken = default(CancellationToken)"));
            body.Append(body.Length == 0 ? "" : "\n");
            body.Append(CultureInfo.InvariantCulture, $"        {returns} {member.AsyncName}({parameters});\n");
        }

        return $$"""
            {{CSharpText.Header}}
            namespace {{layout.ClientNamespace}}
            {
                using System.Threading;
                using System.Threading.Tasks;

                /// <summary>The asynchronous form of <c>{{layout.InterfaceFullName}}</c>: its calls cross the network, so callers should not block on them.</summary>
                public interface {{layout.InterfaceName}}Async
                {
            {{body}}    }
            }

            """;
    }

    private static string Registration(RemoteLayout layout, bool asyncVariant)
    {
        var alsoAsync = asyncVariant
            ? $"\n            services.AddTransient<{layout.InterfaceName}Async>(provider => (Remote{layout.Stem})provider.GetRequiredService<{layout.InterfaceFullName}>());"
            : "";
        return $$"""
            {{CSharpText.Header}}
            namespace {{layout.ClientNamespace}}
            {
                using System;
                using Microsoft.Extensions.Configuration;
                using Microsoft.Extensions.DependencyInjection;

                /// <summary>Registers <c>{{layout.InterfaceFullName}}</c>: the local implementation, or the Windows host over HTTP.</summary>
                public static class {{layout.Stem}}Registration
                {
                    /// <summary>The configuration section of the switch: <c>Mode</c> (<c>local</c> or <c>remote</c>) and <c>Url</c>.</summary>
                    public const string Section = "Remote:{{layout.Stem}}";

                    /// <summary>The interface over HTTP, calling the host at <paramref name="baseAddress"/>.</summary>
                    public static IServiceCollection AddRemote{{layout.Stem}}(this IServiceCollection services, Uri baseAddress)
                    {
                        if (services == null)
                        {
                            throw new ArgumentNullException(nameof(services));
                        }

                        if (baseAddress == null)
                        {
                            throw new ArgumentNullException(nameof(baseAddress));
                        }

                        var root = baseAddress.AbsoluteUri.EndsWith("/", StringComparison.Ordinal) ? baseAddress : new Uri(baseAddress.AbsoluteUri + "/");
                        services.AddHttpClient<{{layout.InterfaceFullName}}, Remote{{layout.Stem}}>(client => client.BaseAddress = root);{{alsoAsync}}
                        return services;
                    }

                    /// <summary>
                    /// The switch, flipped per environment: <c>Remote:{{layout.Stem}}:Mode</c> = <c>remote</c> calls the host at
                    /// <c>Remote:{{layout.Stem}}:Url</c>; anything else registers <paramref name="local"/>.
                    /// </summary>
                    public static IServiceCollection Add{{layout.Stem}}(this IServiceCollection services, IConfiguration configuration, Func<IServiceProvider, {{layout.InterfaceFullName}}> local)
                    {
                        if (configuration == null)
                        {
                            throw new ArgumentNullException(nameof(configuration));
                        }

                        var section = configuration.GetSection(Section);
                        if (string.Equals(section["Mode"], "remote", StringComparison.OrdinalIgnoreCase))
                        {
                            var url = section["Url"];
                            if (string.IsNullOrEmpty(url))
                            {
                                throw new InvalidOperationException(Section + ":Url is required when " + Section + ":Mode is remote.");
                            }

                            return services.AddRemote{{layout.Stem}}(new Uri(url, UriKind.Absolute));
                        }

                        services.AddTransient(local);
                        return services;
                    }
                }
            }

            """;
    }

    private static string SystemTextJsonCall(RemoteLayout layout) => $$"""
        {{CSharpText.Header}}
        namespace {{layout.ClientNamespace}}
        {
            using System.Net.Http;
            using System.Text;
            using System.Text.Json;
            using System.Threading;
            using System.Threading.Tasks;
            using {{layout.ContractsNamespace}};

            /// <summary>POSTs a request as JSON (System.Text.Json, web defaults) and reads the answer; error statuses become <see cref="RemoteInvocationException"/>.</summary>
            internal static class RemoteCall
            {
                private static readonly JsonSerializerOptions Options = new JsonSerializerOptions(JsonSerializerDefaults.Web);

                public static async Task<TResponse> PostAsync<TRequest, TResponse>(HttpClient http, string route, TRequest request, CancellationToken cancellationToken)
                {
                    var body = await SendAsync(http, route, request, cancellationToken).ConfigureAwait(false);
                    return body.Length == 0 ? default(TResponse) : JsonSerializer.Deserialize<TResponse>(body, Options);
                }

                public static async Task PostAsync<TRequest>(HttpClient http, string route, TRequest request, CancellationToken cancellationToken)
                {
                    await SendAsync(http, route, request, cancellationToken).ConfigureAwait(false);
                }

                private static async Task<string> SendAsync<TRequest>(HttpClient http, string route, TRequest request, CancellationToken cancellationToken)
                {
                    using (var content = new StringContent(JsonSerializer.Serialize(request, Options), Encoding.UTF8, "application/json"))
                    using (var response = await http.PostAsync(route, content, cancellationToken).ConfigureAwait(false))
                    {
                        var body = response.Content == null ? "" : await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                        if (!response.IsSuccessStatusCode)
                        {
                            string title;
                            string detail;
                            Problem(body, out title, out detail);
                            throw new RemoteInvocationException(route, (int)response.StatusCode, title ?? response.ReasonPhrase, detail);
                        }

                        return body;
                    }
                }

                /// <summary>The title and detail of a problem details body (or the message of an ASP.NET Web API error).</summary>
                private static void Problem(string body, out string title, out string detail)
                {
                    title = null;
                    detail = null;
                    try
                    {
                        using (var document = JsonDocument.Parse(body))
                        {
                            if (document.RootElement.ValueKind != JsonValueKind.Object)
                            {
                                return;
                            }

                            title = Text(document.RootElement, "title") ?? Text(document.RootElement, "message") ?? Text(document.RootElement, "Message");
                            detail = Text(document.RootElement, "detail");
                        }
                    }
                    catch (JsonException)
                    {
                    }
                }

                private static string Text(JsonElement element, string name)
                {
                    JsonElement value;
                    return element.TryGetProperty(name, out value) && value.ValueKind == JsonValueKind.String ? value.GetString() : null;
                }
            }
        }

        """;

    private static string NewtonsoftCall(RemoteLayout layout) => $$"""
        {{CSharpText.Header}}
        namespace {{layout.ClientNamespace}}
        {
            using System.Net.Http;
            using System.Text;
            using System.Threading;
            using System.Threading.Tasks;
            using Newtonsoft.Json;
            using Newtonsoft.Json.Linq;
            using Newtonsoft.Json.Serialization;
            using {{layout.ContractsNamespace}};

            /// <summary>POSTs a request as JSON (Newtonsoft.Json, camelCase) and reads the answer; error statuses become <see cref="RemoteInvocationException"/>.</summary>
            internal static class RemoteCall
            {
                private static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
                {
                    ContractResolver = new DefaultContractResolver { NamingStrategy = new CamelCaseNamingStrategy { ProcessDictionaryKeys = false } },
                };

                public static async Task<TResponse> PostAsync<TRequest, TResponse>(HttpClient http, string route, TRequest request, CancellationToken cancellationToken)
                {
                    var body = await SendAsync(http, route, request, cancellationToken).ConfigureAwait(false);
                    return body.Length == 0 ? default(TResponse) : JsonConvert.DeserializeObject<TResponse>(body, Settings);
                }

                public static async Task PostAsync<TRequest>(HttpClient http, string route, TRequest request, CancellationToken cancellationToken)
                {
                    await SendAsync(http, route, request, cancellationToken).ConfigureAwait(false);
                }

                private static async Task<string> SendAsync<TRequest>(HttpClient http, string route, TRequest request, CancellationToken cancellationToken)
                {
                    using (var content = new StringContent(JsonConvert.SerializeObject(request, Settings), Encoding.UTF8, "application/json"))
                    using (var response = await http.PostAsync(route, content, cancellationToken).ConfigureAwait(false))
                    {
                        var body = response.Content == null ? "" : await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                        if (!response.IsSuccessStatusCode)
                        {
                            string title;
                            string detail;
                            Problem(body, out title, out detail);
                            throw new RemoteInvocationException(route, (int)response.StatusCode, title ?? response.ReasonPhrase, detail);
                        }

                        return body;
                    }
                }

                /// <summary>The title and detail of a problem details body (or the message of an ASP.NET Web API error).</summary>
                private static void Problem(string body, out string title, out string detail)
                {
                    title = null;
                    detail = null;
                    try
                    {
                        var problem = JToken.Parse(body) as JObject;
                        if (problem == null)
                        {
                            return;
                        }

                        title = (string)(problem["title"] ?? problem["message"] ?? problem["Message"]);
                        detail = (string)problem["detail"];
                    }
                    catch (JsonException)
                    {
                    }
                }
            }
        }

        """;

    private static string Parameter(IParameterSymbol parameter)
    {
        var modifier = parameter.IsParams ? "params " : "";
        return $"{modifier}{CSharpText.Type(parameter.Type)} {CSharpText.Identifier(parameter.Name)}";
    }
}
