using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Offramp.Scaffolding.Text;

namespace Offramp.Scaffolding.Remote;

/// <summary>The contracts project (netstandard2.0): routes, requests, DTOs, and the client's error type.</summary>
internal static class ContractsTemplate
{
    public static IEnumerable<(string Path, string Text)> Files(RemoteLayout layout, IReadOnlyList<BoundaryMember> members, WireTypes wire)
    {
        var directory = layout.ContractsDirectory;
        yield return ($"{layout.ContractsProject}", Project(layout));
        yield return ($"{directory}/{layout.Stem}Routes.cs", Routes(layout, members));
        yield return ($"{directory}/{layout.Stem}Requests.cs", Requests(layout, members, wire));
        if (wire.Dtos.Count > 0)
        {
            yield return ($"{directory}/{layout.Stem}Dtos.cs", Dtos(layout, wire));
        }

        yield return ($"{directory}/RemoteInvocationException.cs", Exception(layout));
    }

    private static string Project(RemoteLayout layout) => $$"""
        <Project Sdk="Microsoft.NET.Sdk">
          <!-- Generated by offramp remote: the wire contract of {{layout.InterfaceFullName}} (routes, requests, DTOs). -->
          <PropertyGroup>
            <TargetFramework>netstandard2.0</TargetFramework>
            <LangVersion>latest</LangVersion>
            <Nullable>disable</Nullable>
            <RootNamespace>{{layout.ContractsNamespace}}</RootNamespace>
          </PropertyGroup>
        </Project>

        """;

    private static string Routes(RemoteLayout layout, IReadOnlyList<BoundaryMember> members)
    {
        var body = new StringBuilder();
        foreach (var member in members.Where(m => m.Status == "remote"))
        {
            if (body.Length > 0)
            {
                body.Append('\n');
            }

            body.Append(CultureInfo.InvariantCulture, $"        /// <summary><c>{Escape(Signature(member))}</c></summary>\n");
            body.Append(CultureInfo.InvariantCulture, $"        public const string {member.Key} = \"{layout.Route(member)}\";\n");
        }

        return $$"""
            {{CSharpText.Header}}
            namespace {{layout.ContractsNamespace}}
            {
                /// <summary>The HTTP routes of <c>{{layout.InterfaceFullName}}</c>: one POST per member, relative to the host's base address.</summary>
                public static class {{layout.Stem}}Routes
                {
            {{body.ToString().TrimEnd('\n')}}
                }
            }

            """;
    }

    private static string Requests(RemoteLayout layout, IReadOnlyList<BoundaryMember> members, WireTypes wire)
    {
        var body = new StringBuilder();
        foreach (var member in members.Where(m => m.Status == "remote"))
        {
            if (body.Length > 0)
            {
                body.Append('\n');
            }

            body.Append(CultureInfo.InvariantCulture, $"    /// <summary>The arguments of <c>{Escape(layout.InterfaceName + "." + member.Symbol.Name)}</c>.</summary>\n");
            body.Append(CultureInfo.InvariantCulture, $"    public sealed class {member.Key}Request\n    {{\n");
            var first = true;
            foreach (var argument in member.Arguments.Where(a => a.Property is not null))
            {
                if (!first)
                {
                    body.Append('\n');
                }

                first = false;
                body.Append(CultureInfo.InvariantCulture, $"        public {wire.WireType(argument.Parameter.Type)} {argument.Property} {{ get; set; }}\n");
            }

            body.Append("    }\n");
        }

        return $$"""
            {{CSharpText.Header}}
            namespace {{layout.ContractsNamespace}}
            {
            {{body.ToString().TrimEnd('\n')}}
            }

            """;
    }

    private static string Dtos(RemoteLayout layout, WireTypes wire)
    {
        var body = new StringBuilder();
        foreach (var (type, dto) in wire.Dtos)
        {
            if (body.Length > 0)
            {
                body.Append('\n');
            }

            body.Append(CultureInfo.InvariantCulture, $"    /// <summary>The wire form of <c>{Escape(CSharpText.Type(type))}</c>.</summary>\n");
            if (type.TypeKind == TypeKind.Enum)
            {
                if (type.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == "System.FlagsAttribute"))
                {
                    body.Append("    [System.Flags]\n");
                }

                var underlying = type.EnumUnderlyingType is { SpecialType: not SpecialType.System_Int32 } u ? " : " + CSharpText.Type(u) : "";
                body.Append(CultureInfo.InvariantCulture, $"    public enum {dto}{underlying}\n    {{\n");
                foreach (var field in type.GetMembers().OfType<IFieldSymbol>().Where(f => f.HasConstantValue))
                {
                    body.Append(CultureInfo.InvariantCulture, $"        {CSharpText.Identifier(field.Name)} = {Convert.ToString(field.ConstantValue, CultureInfo.InvariantCulture)},\n");
                }

                body.Append("    }\n");
                continue;
            }

            body.Append(CultureInfo.InvariantCulture, $"    public sealed class {dto}\n    {{\n");
            var first = true;
            foreach (var property in WireTypes.Properties(type))
            {
                if (!first)
                {
                    body.Append('\n');
                }

                first = false;
                body.Append(CultureInfo.InvariantCulture, $"        public {wire.WireType(property.Type)} {CSharpText.Identifier(property.Name)} {{ get; set; }}\n");
            }

            body.Append("    }\n");
        }

        return $$"""
            {{CSharpText.Header}}
            namespace {{layout.ContractsNamespace}}
            {
            {{body.ToString().TrimEnd('\n')}}
            }

            """;
    }

    private static string Exception(RemoteLayout layout) => $$"""
        {{CSharpText.Header}}
        namespace {{layout.ContractsNamespace}}
        {
            /// <summary>The host answered a remote call with an error status; carries its problem details when it sent them.</summary>
            public sealed class RemoteInvocationException : System.Exception
            {
                public RemoteInvocationException(string route, int statusCode, string title, string detail)
                    : base(route + " failed with " + statusCode + (string.IsNullOrEmpty(title) ? "" : ": " + title) + (string.IsNullOrEmpty(detail) ? "" : " (" + detail + ")"))
                {
                    Route = route;
                    StatusCode = statusCode;
                    Title = title;
                    Detail = detail;
                }

                public string Route { get; }

                public int StatusCode { get; }

                public string Title { get; }

                public string Detail { get; }
            }
        }

        """;

    /// <summary>The member as C# declares it, for doc comments.</summary>
    public static string Signature(BoundaryMember member) => Offramp.Analysis.Seams.SeamsAnalyzer.Signature(member.Symbol);

    public static string Escape(string text) => text.Replace("&", "&amp;", StringComparison.Ordinal).Replace("<", "&lt;", StringComparison.Ordinal).Replace(">", "&gt;", StringComparison.Ordinal);
}
