using Offramp.Scaffolding.Text;

namespace Offramp.Scaffolding.Remote;

/// <summary>Container assets for the host (<c>--container</c>): a Windows Dockerfile and a Kubernetes Deployment and Service.</summary>
internal static class ContainerTemplate
{
    public static IEnumerable<(string Path, string Text)> Files(RemoteLayout layout, bool modern)
    {
        yield return ($"{layout.HostDirectory}/Dockerfile", modern ? ModernDockerfile(layout) : LegacyDockerfile(layout));
        yield return ($"{layout.HostDirectory}/kubernetes.yaml", Kubernetes(layout));
    }

    private static string ModernDockerfile(RemoteLayout layout) => $$"""
        # Generated by offramp remote. Build from the repository root on a Windows container host:
        #   docker build -f {{layout.HostDirectory}}/Dockerfile -t {{CSharpText.Kebab(layout.HostName)}} .
        # Nano Server lacks some Windows components (the Active Directory client, GDI+, COM servers);
        # if the implementation needs them, use the windowsservercore-ltsc2022 tags for both images.
        FROM mcr.microsoft.com/dotnet/sdk:10.0-nanoserver-ltsc2022 AS build
        WORKDIR /src
        COPY . .
        RUN dotnet publish {{layout.HostProject}} -c Release -o /app

        FROM mcr.microsoft.com/dotnet/aspnet:10.0-nanoserver-ltsc2022
        WORKDIR /app
        COPY --from=build /app .
        ENV ASPNETCORE_HTTP_PORTS=8080
        EXPOSE 8080
        ENTRYPOINT ["dotnet", "{{layout.HostName}}.dll"]

        """;

    private static string LegacyDockerfile(RemoteLayout layout) => $$"""
        # Generated by offramp remote (legacy net48 host). Build from the repository root on a Windows container host:
        #   docker build -f {{layout.HostDirectory}}/Dockerfile -t {{CSharpText.Kebab(layout.HostName)}} .
        FROM mcr.microsoft.com/dotnet/framework/sdk:4.8 AS build
        WORKDIR /src
        COPY . .
        RUN dotnet publish {{layout.HostProject}} -c Release -o /app

        FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8
        WORKDIR /app
        COPY --from=build /app .
        ENV OFFRAMP_HOST_URL=http://+:8080/
        EXPOSE 8080
        ENTRYPOINT ["{{layout.HostName}}.exe"]

        """;

    private static string Kubernetes(RemoteLayout layout)
    {
        var name = CSharpText.Kebab(layout.HostName);
        return $$"""
            # Generated by offramp remote: {{layout.HostName}} on Windows nodes, behind a Service the clients call.
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: {{name}}
              labels:
                app: {{name}}
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: {{name}}
              template:
                metadata:
                  labels:
                    app: {{name}}
                spec:
                  nodeSelector:
                    kubernetes.io/os: windows
                  containers:
                    - name: host
                      image: {{name}}:latest
                      ports:
                        - containerPort: 8080
                      resources:
                        requests:
                          cpu: 250m
                          memory: 256Mi
                        limits:
                          memory: 1Gi
                      readinessProbe:
                        httpGet:
                          path: /health
                          port: 8080
                        initialDelaySeconds: 10
                        periodSeconds: 10
            ---
            apiVersion: v1
            kind: Service
            metadata:
              name: {{name}}
            spec:
              selector:
                app: {{name}}
              ports:
                - port: 80
                  targetPort: 8080

            """;
    }
}
