using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Offramp.Core.Paths;
using Offramp.Scaffolding.Text;

namespace Offramp.Scaffolding.Remote;

/// <summary>
/// The Windows host: an ASP.NET Core minimal API on net10.0-windows that compiles the
/// implementation's files as links, or the legacy fallback on net48 (OWIN self-host with ASP.NET
/// Web API 2) that references the implementation's project.
/// </summary>
internal static class HostTemplate
{
    public static IEnumerable<(string Path, string Text)> Modern(RemoteLayout layout, IReadOnlyList<BoundaryMember> members, WireTypes wire, HostTrial trial, string repositoryRoot)
    {
        var directory = layout.HostDirectory;
        yield return (layout.HostProject, ModernProject(layout, trial, repositoryRoot));
        yield return ($"{directory}/Program.cs", ModernProgram(layout));
        yield return ($"{directory}/{layout.Stem}Endpoints.cs", Endpoints(layout, members, wire));
        yield return ($"{directory}/{layout.Stem}Mapping.cs", MappingTemplate.Text(layout, wire, layout.HostNamespace));
        yield return ($"{directory}/appsettings.json", """
            {
              "Logging": {
                "LogLevel": {
                  "Default": "Information",
                  "Microsoft.AspNetCore": "Warning"
                }
              },
              "AllowedHosts": "*"
            }

            """);
    }

    public static IEnumerable<(string Path, string Text)> Legacy(RemoteLayout layout, IReadOnlyList<BoundaryMember> members, WireTypes wire)
    {
        var directory = layout.HostDirectory;
        yield return (layout.HostProject, LegacyProject(layout));
        yield return ($"{directory}/Program.cs", LegacyProgram(layout));
        yield return ($"{directory}/{layout.Stem}Controller.cs", Controller(layout, members, wire));
        yield return ($"{directory}/{layout.Stem}Mapping.cs", MappingTemplate.Text(layout, wire, layout.HostNamespace));
    }

    private static string ModernProject(RemoteLayout layout, HostTrial trial, string repositoryRoot)
    {
        var packages = new StringBuilder();
        foreach (var (id, version) in trial.Packages.OrderBy(p => p.Id, StringComparer.OrdinalIgnoreCase))
        {
            packages.Append(CultureInfo.InvariantCulture, $"    <PackageReference Include=\"{id}\" Version=\"{version}\" />\n");
        }

        var projectDirectory = RepoPaths.Normalize(Path.GetDirectoryName(layout.ProjectFile) ?? "");
        var links = new StringBuilder();
        foreach (var tree in trial.Sources)
        {
            var file = Path.IsPathRooted(tree.FilePath) ? RepoPaths.ToRepositoryRelative(repositoryRoot, Path.GetFullPath(tree.FilePath)) : RepoPaths.Normalize(tree.FilePath);
            var inProject = projectDirectory.Length == 0 ? file : file.StartsWith(projectDirectory + "/", StringComparison.Ordinal) ? file[(projectDirectory.Length + 1)..] : Path.GetFileName(file);
            links.Append(CultureInfo.InvariantCulture, $"    <Compile Include=\"{RemoteLayout.Relative(layout.HostDirectory, file)}\" Link=\"Implementation\\{inProject.Replace('/', '\\')}\" />\n");
        }

        return $$"""
            <Project Sdk="Microsoft.NET.Sdk.Web">
              <!-- Generated by offramp remote: runs {{layout.ImplementationFullName}} on Windows behind {{layout.InterfaceFullName}} over HTTP. -->
              <PropertyGroup>
                <TargetFramework>net10.0-windows</TargetFramework>
                <!-- Builds on Linux and macOS too; it runs on Windows. -->
                <EnableWindowsTargeting>true</EnableWindowsTargeting>
                <Nullable>disable</Nullable>
                <ImplicitUsings>disable</ImplicitUsings>
                <RootNamespace>{{layout.HostNamespace}}</RootNamespace>
            {{CentralPackages(layout)}}  </PropertyGroup>

              <ItemGroup>
            {{packages}}  </ItemGroup>

              <ItemGroup>
                <ProjectReference Include="{{RemoteLayout.Relative(layout.HostDirectory, layout.ContractsProject)}}" />
              </ItemGroup>

              <!-- The implementation and the files it uses, compiled from {{layout.ProjectFile}} until they move to a project of their own. -->
              <ItemGroup>
            {{links}}  </ItemGroup>
            </Project>

            """;
    }

    private static string ModernProgram(RemoteLayout layout)
    {
        var construct = layout.Implementation.InstanceConstructors.Any(c => c.DeclaredAccessibility == Accessibility.Public)
            ? $"builder.Services.AddScoped<{layout.InterfaceFullName}, {layout.ImplementationFullName}>();"
            : $"builder.Services.AddScoped<{layout.InterfaceFullName}>(provider => throw new System.InvalidOperationException(\"{layout.Implementation.Name} has no public constructor: register a factory here.\"));";
        return $$"""
            {{CSharpText.Header}}
            using Microsoft.AspNetCore.Builder;
            using Microsoft.AspNetCore.Http;
            using Microsoft.Extensions.DependencyInjection;
            using Microsoft.Extensions.Logging;

            var builder = WebApplication.CreateBuilder(args);
            builder.Logging.ClearProviders();
            builder.Logging.AddJsonConsole();
            builder.Services.AddProblemDetails();

            // A new implementation per request, as callers that create it with new get one.
            {{construct}}

            var app = builder.Build();
            app.UseExceptionHandler();
            app.MapGet("/health", () => Results.Ok(new { status = "healthy" }));
            {{layout.HostNamespace}}.{{layout.Stem}}Endpoints.Map(app);
            app.Run();

            /// <summary>The entry point; public so that tests can host it with WebApplicationFactory.</summary>
            public partial class Program
            {
            }

            """;
    }

    private static string Endpoints(RemoteLayout layout, IReadOnlyList<BoundaryMember> members, WireTypes wire)
    {
        var body = new StringBuilder();
        foreach (var member in members.Where(m => m.Status == "remote"))
        {
            var method = member.Method!;
            var token = member.Arguments.Any(a => a.Property is null);
            var parameters = $"[FromBody] {layout.Request(member)} request, [FromServices] {layout.InterfaceFullName} service" + (token ? ", CancellationToken cancellationToken" : "");
            var call = $"service.{CSharpText.Identifier(method.Name)}({Arguments(member, wire)})";
            if (member.Async)
            {
                call = "await " + call;
            }

            var handler = member.Returns is { } returns
                ? $"Results.Json({wire.ToWire(returns, call)})"
                : $"{{\n                {call};\n                return Results.NoContent();\n            }}";
            body.Append(CultureInfo.InvariantCulture, $"            endpoints.MapPost({layout.Routes}.{member.Key}, {(member.Async ? "async " : "")}({parameters}) =>");
            body.Append(member.Returns is null ? "\n            " + handler + ");\n" : "\n                " + handler + ");\n");
        }

        return $$"""
            {{CSharpText.Header}}
            namespace {{layout.HostNamespace}}
            {
                using System.Threading;
                using Microsoft.AspNetCore.Builder;
                using Microsoft.AspNetCore.Http;
                using Microsoft.AspNetCore.Mvc;
                using Microsoft.AspNetCore.Routing;

                /// <summary>The routes of <c>{{layout.InterfaceFullName}}</c>: each POST calls the implementation.</summary>
                public static class {{layout.Stem}}Endpoints
                {
                    public static IEndpointRouteBuilder Map(IEndpointRouteBuilder endpoints)
                    {
            {{body}}            return endpoints;
                    }
                }
            }

            """;
    }

    private static string LegacyProject(RemoteLayout layout) => $$"""
        <Project Sdk="Microsoft.NET.Sdk">
          <!-- Generated by offramp remote: the legacy net48 host for {{layout.ImplementationFullName}} (OWIN self-host, ASP.NET Web API 2). -->
          <PropertyGroup>
            <OutputType>Exe</OutputType>
            <TargetFramework>net48</TargetFramework>
            <LangVersion>latest</LangVersion>
            <Nullable>disable</Nullable>
            <RootNamespace>{{layout.HostNamespace}}</RootNamespace>
        {{CentralPackages(layout)}}  </PropertyGroup>

          <ItemGroup>
            <PackageReference Include="Microsoft.AspNet.WebApi.OwinSelfHost" Version="{{ScaffoldPackages.Version("Microsoft.AspNet.WebApi.OwinSelfHost")}}" />
          </ItemGroup>

          <ItemGroup>
            <ProjectReference Include="{{RemoteLayout.Relative(layout.HostDirectory, layout.ProjectFile)}}" />
            <ProjectReference Include="{{RemoteLayout.Relative(layout.HostDirectory, layout.ContractsProject)}}" />
          </ItemGroup>
        </Project>

        """;

    private static string LegacyProgram(RemoteLayout layout) => $$"""
        {{CSharpText.Header}}
        namespace {{layout.HostNamespace}}
        {
            using System;
            using System.Net;
            using System.Net.Http;
            using System.Web.Http;
            using System.Web.Http.Filters;
            using Microsoft.Owin.Hosting;
            using Newtonsoft.Json.Serialization;
            using Owin;

            /// <summary>
            /// The legacy fallback host (net48, OWIN self-host with ASP.NET Web API 2), generated because the
            /// implementation does not compile for net10.0-windows yet. Listens on the URL in the first
            /// argument or OFFRAMP_HOST_URL (default http://+:8080/).
            /// </summary>
            public static class Program
            {
                public static void Main(string[] args)
                {
                    var url = args.Length > 0 ? args[0] : Environment.GetEnvironmentVariable("OFFRAMP_HOST_URL") ?? "http://+:8080/";
                    using (WebApp.Start<Startup>(url))
                    {
                        Console.WriteLine("Listening on " + url + ". Press Enter to stop.");
                        Console.ReadLine();
                    }
                }
            }

            /// <summary>Web API with attribute routes, camelCase JSON, and problem details for failures.</summary>
            public sealed class Startup
            {
                public void Configuration(IAppBuilder app)
                {
                    var config = new HttpConfiguration();
                    config.MapHttpAttributeRoutes();
                    config.Formatters.Remove(config.Formatters.XmlFormatter);
                    config.Formatters.JsonFormatter.SerializerSettings.ContractResolver = new DefaultContractResolver
                    {
                        NamingStrategy = new CamelCaseNamingStrategy { ProcessDictionaryKeys = false },
                    };
                    config.Filters.Add(new ProblemDetailsFilter());
                    app.UseWebApi(config);
                }
            }

            /// <summary>Answers /health for readiness probes.</summary>
            public sealed class HealthController : ApiController
            {
                [HttpGet]
                [Route("health")]
                public IHttpActionResult Get()
                {
                    return Ok(new { status = "healthy" });
                }
            }

            /// <summary>Unhandled exceptions become 500 problem details, as the net10.0-windows host answers.</summary>
            public sealed class ProblemDetailsFilter : ExceptionFilterAttribute
            {
                public override void OnException(HttpActionExecutedContext actionExecutedContext)
                {
                    var problem = new { type = "https://tools.ietf.org/html/rfc9110#section-15.6.1", title = "An error occurred while processing your request.", status = 500 };
                    actionExecutedContext.Response = actionExecutedContext.Request.CreateResponse(HttpStatusCode.InternalServerError, problem);
                }
            }
        }

        """;

    private static string Controller(RemoteLayout layout, IReadOnlyList<BoundaryMember> members, WireTypes wire)
    {
        var factory = layout.Implementation.InstanceConstructors.Any(c => c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public)
            ? $"() => new {layout.ImplementationFullName}()"
            : $"() => throw new InvalidOperationException(\"Set {layout.Stem}Controller.Factory: {layout.Implementation.Name} has no public parameterless constructor.\")";
        var body = new StringBuilder();
        foreach (var member in members.Where(m => m.Status == "remote"))
        {
            var method = member.Method!;
            var token = member.Arguments.Any(a => a.Property is null);
            var call = $"service.{CSharpText.Identifier(method.Name)}({Arguments(member, wire)})";
            if (member.Async)
            {
                call = "await " + call;
            }

            var returns = member.Returns is { } r ? wire.WireType(r) : "IHttpActionResult";
            var signature = member.Async ? $"async Task<{returns}>" : returns;
            body.Append(CultureInfo.InvariantCulture, $"\n        [HttpPost]\n        [Route({layout.Routes}.{member.Key})]\n");
            body.Append(CultureInfo.InvariantCulture, $"        public {signature} {member.Key}([FromBody] {layout.Request(member)} request{(token ? ", CancellationToken cancellationToken" : "")})\n        {{\n");
            body.Append("            var service = Factory();\n");
            if (member.Returns is { } value)
            {
                body.Append(CultureInfo.InvariantCulture, $"            return {wire.ToWire(value, call)};\n");
            }
            else
            {
                body.Append(CultureInfo.InvariantCulture, $"            {call};\n            return StatusCode(HttpStatusCode.NoContent);\n");
            }

            body.Append("        }\n");
        }

        return $$"""
            {{CSharpText.Header}}
            namespace {{layout.HostNamespace}}
            {
                using System;
                using System.Net;
                using System.Threading;
                using System.Threading.Tasks;
                using System.Web.Http;

                /// <summary>The routes of <c>{{layout.InterfaceFullName}}</c>: each POST calls the implementation.</summary>
                public sealed class {{layout.Stem}}Controller : ApiController
                {
                    /// <summary>Creates the implementation for each request; replace it to supply the implementation's dependencies.</summary>
                    public static Func<{{layout.InterfaceFullName}}> Factory = {{factory}};
            {{body}}    }
            }

            """;
    }

    /// <summary>Arguments of the implementation call: request properties converted back, the request's cancellation token.</summary>
    private static string Arguments(BoundaryMember member, WireTypes wire) =>
        string.Join(", ", member.Arguments.Select(a => a.Property is null ? "cancellationToken" : wire.FromWire(a.Parameter.Type, "request." + a.Property)));

    public static string CentralPackages(RemoteLayout layout) => layout.CentralPackages
        ? "    <!-- Pins its own package versions; `offramp deps consolidate --cpm` can centralize them. -->\n    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>\n"
        : "";
}
