<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Evidence.Shop</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Engine\Engine.csproj" />
    <ProjectReference Include="..\Client\Client.csproj" />
    <ProjectReference Include="..\Tools\Tools.csproj" />
  </ItemGroup>
</Project>
