//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the release script.
//     Changes to this file are lost when it runs again.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyInformationalVersion("4.1.2-dev")]
