<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Offramp.Cli.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Offramp.Cli\Offramp.Cli.csproj" />
    <ProjectReference Include="..\Offramp.Fixtures\Offramp.Fixtures.csproj" />
  </ItemGroup>
</Project>
