<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Offramp.Scaffolding.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Offramp.Scaffolding\Offramp.Scaffolding.csproj" />
    <ProjectReference Include="..\Offramp.Fixtures\Offramp.Fixtures.csproj" />
  </ItemGroup>
</Project>
