namespace Offramp.Core.Diagnostics;

public static partial class DiagnosticCatalog
{
    private const string ReportingArea = "graph/report";

    public static readonly DiagnosticDescriptor OFR0201 = new(
        "OFR0201", Severity.Info,
        "graph too large for Mermaid",
        "The Mermaid graph has more than 300 projects; Mermaid renderers become slow and unreadable at that size.",
        "`graph --format mermaid` on a large solution without a focus or kind filter.",
        "Narrow the view with `--focus PROJECT --depth N` or `--exclude-kind test`, or use `--format html`.",
        ReportingArea);

    public static readonly DiagnosticDescriptor OFR0202 = new(
        "OFR0202", Severity.Warning,
        "ledger file is not a snapshot",
        "A JSON file in the ledger directory could not be read as a ledger snapshot, so the report leaves it out of the burn-down.",
        "A hand-edited or truncated snapshot, a merge conflict left in a committed snapshot, or an unrelated JSON file in `report.ledger`.",
        "Fix or delete the file (snapshots are regenerated by `offramp scan`), or keep other files outside the ledger directory.",
        ReportingArea);

    public static readonly DiagnosticDescriptor OFR0203 = new(
        "OFR0203", Severity.Info,
        "ledger snapshots of another solution left out",
        "The ledger holds snapshots of scans of another solution or solution filter than the current model's. Their projects differ, so `report` leaves them out of the trend instead of reading the difference as progress.",
        "Scanning a solution filter or another solution of the repository (`scan --solution`, or a changed `solution:`), then scanning the main one.",
        "Nothing to do; the snapshots stay in the ledger for a report on that solution. Delete them from `report.ledger` if that scan was a one-off.",
        ReportingArea);

    public static readonly DiagnosticDescriptor OFR0204 = new(
        "OFR0204", Severity.Info,
        "hosted project is part of its host's application",
        "The project builds into another web project's folder (its `bin/` or a folder such as `Plugins/<Name>/`) and has no `Global.asax` of its own: the host's application loads it at run time. `report` counts it in the host's application instead of as an application, `plan --for` the host lists it, and `web inventory` names the host.",
        "Plugins, modules, and MVC areas in projects of their own that build into the site: SmartStoreNET's and nopCommerce's plugins, DotNetNuke's modules.",
        "Nothing to do. Run `plan --for` or `web scaffold` on the host for the application; set the project's `kind` in `offramp.yml` if it really is an application of its own.",
        ReportingArea);

    public static readonly DiagnosticDescriptor OFR0205 = new(
        "OFR0205", Severity.Warning,
        "web scaffold of a hosted project",
        "The project is hosted by another web project: on its own it serves nothing, so the new application's proxy forwards to the host's URL instead of the project's, and the actions it ports are the hosted project's only.",
        "`web scaffold --project` naming a plugin, module, or area project instead of the site that loads it.",
        "Scaffold the host (`web scaffold --project HOST`) to put the whole application behind the new one, or keep this scaffold for the hosted project's routes and check `--legacy-url`.",
        "web");
}
