namespace Offramp.Core.Diagnostics;

public static partial class DiagnosticCatalog
{
    private const string ReportingArea = "graph/report";

    public static readonly DiagnosticDescriptor OFR0201 = new(
        "OFR0201", Severity.Info,
        "graph too large for Mermaid",
        "The Mermaid graph has more than 300 projects; Mermaid renderers become slow and unreadable at that size.",
        "`graph --format mermaid` on a large solution without a focus or kind filter.",
        "Narrow the view with `--focus PROJECT --depth N` or `--exclude-kind test`, or use `--format html`.",
        ReportingArea);

    public static readonly DiagnosticDescriptor OFR0202 = new(
        "OFR0202", Severity.Warning,
        "ledger file is not a snapshot",
        "A JSON file in the ledger directory could not be read as a ledger snapshot, so the report leaves it out of the burn-down.",
        "A hand-edited or truncated snapshot, a merge conflict left in a committed snapshot, or an unrelated JSON file in `report.ledger`.",
        "Fix or delete the file (snapshots are regenerated by `offramp scan`), or keep other files outside the ledger directory.",
        ReportingArea);
}
