namespace Offramp.Core.Diagnostics;

public static partial class DiagnosticCatalog
{
    private const string ConfigConvertArea = "config convert";

    public static readonly DiagnosticDescriptor OFR4401 = new(
        "OFR4401", Severity.Warning,
        "setting not representable",
        "A configuration section, or one of its properties, has no faithful appsettings.json form: its section type is not in the solution, it is an element collection, it uses a custom TypeConverter, or its value does not parse as the property's type. It is left out of the JSON and the options class.",
        "Custom section handlers, `ConfigurationElementCollection`s, converters for domain types.",
        "Add the setting to appsettings.json by hand in the shape the new code reads, and bind it to an options class you write.",
        ConfigConvertArea);

    public static readonly DiagnosticDescriptor OFR4402 = new(
        "OFR4402", Severity.Warning,
        "WCF configuration",
        "`system.serviceModel` configures WCF clients and services; modern .NET has no configuration-file WCF. Clients are configured in code (System.ServiceModel.Http packages) and services move to CoreWCF.",
        "WCF clients generated by Add Service Reference, WCF-hosted services.",
        "Configure the client binding and endpoint in code; for services, see CoreWCF's configuration support.",
        ConfigConvertArea);

    public static readonly DiagnosticDescriptor OFR4403 = new(
        "OFR4403", Severity.Info,
        "system.web settings belong to the web migration",
        "`system.web` and `system.webServer` configure ASP.NET and IIS: authentication, session, handlers, modules. Their ASP.NET Core counterparts are middleware and hosting settings, generated by `web scaffold`, not configuration values.",
        "ASP.NET applications.",
        "Run `offramp web inventory` and `offramp web scaffold` for the web application.",
        ConfigConvertArea);

    public static readonly DiagnosticDescriptor OFR4404 = new(
        "OFR4404", Severity.Warning,
        "config transform not expressible as overrides",
        "A transform file (Web.Release.config) does something an appsettings.{Environment}.json override cannot: it inserts or removes elements outside appSettings and connectionStrings, uses XPath locators, or transforms sections with no JSON form. The parts that are overrides are converted; the rest is listed.",
        "Transforms that remove debug settings or rewrite system.web.",
        "Express the rest as environment-specific configuration or deployment settings by hand.",
        ConfigConvertArea);

    public static readonly DiagnosticDescriptor OFR4405 = new(
        "OFR4405", Severity.Error,
        "no configuration file",
        "`config convert` looks for App.config or Web.config in the project's folder and found neither.",
        "A project that reads no configuration, or a configuration file with another name.",
        "Pass the project that owns the configuration file.",
        ConfigConvertArea);

    public static readonly DiagnosticDescriptor OFR4406 = new(
        "OFR4406", Severity.Error,
        "output file exists",
        "A file `config convert` would write (appsettings.json, an environment file, the options or shim class) already exists, so nothing was written.",
        "A second run, or a project that already has appsettings.json.",
        "Write to another folder with --out, or move the existing file aside and merge by hand.",
        ConfigConvertArea);
}
