<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>Portal</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Accounts\Accounts.csproj" />
  </ItemGroup>
</Project>
