using System.Globalization;
using System.Net;
using System.Text;

namespace Offramp.Reporting.Report;

/// <summary>
/// The report as one self-contained, script-free HTML page: headline numbers, the
/// burn-down, framework class by area, applications, and the frontier. With a graph
/// page, it is embedded in a sandboxed <c>iframe srcdoc</c> so its scripts stay its own.
/// </summary>
public static class HtmlReportWriter
{
    public static string Write(ReportData report, string? graphHtml = null)
    {
        var body = new StringBuilder();
        Header(body, report);
        Headline(body, report);
        BurnDown(body, report);
        Areas(body, report);
        Applications(body, report);
        Frontier(body, report);
        if (graphHtml is not null)
        {
            body.Append("<section class=\"graph-section\">\n<h2>Dependency graph</h2>\n")
                .Append("<p class=\"note\">Tests left out; projects that can be ported today are highlighted.</p>\n")
                .Append("<iframe class=\"graph\" title=\"Dependency graph\" sandbox=\"allow-scripts allow-downloads\" srcdoc=\"")
                .Append(WebUtility.HtmlEncode(graphHtml)).Append("\"></iframe>\n</section>\n");
        }

        body.Append("<footer>Generated by offramp from ").Append(ReportText.Count(report.Series.Count, "scan"))
            .Append(". Lines of code are all lines in the files each project compiles.</footer>");
        return Resources.Read("report.html")
            .Replace("{{TITLE}}", Encode(report.Title), StringComparison.Ordinal)
            .Replace("{{BODY}}", body.ToString(), StringComparison.Ordinal);
    }

    private static void Header(StringBuilder body, ReportData report)
    {
        body.Append("<header>\n<h1>").Append(Encode(report.Title)).Append("</h1>\n<p class=\"meta\">As of ")
            .Append(ReportText.Moment(report.AsOf)).Append(" UTC");
        if (report.Since is not null)
        {
            body.Append(" · since ").Append(Encode(report.Since));
        }

        body.Append("</p>\n</header>\n");
    }

    private static void Headline(StringBuilder body, ReportData report)
    {
        var h = report.Headline;
        body.Append("<section class=\"tiles\" aria-label=\"Headline numbers\">\n");
        Tile(body, h.PortablePercent.ToString("0.#", CultureInfo.InvariantCulture) + "%",
            "of " + ReportText.Count(h.Loc, "line") + " in portable projects (standard, modern, dual)");
        Tile(body, h.FrameworkLoc.ToString("N0", CultureInfo.InvariantCulture),
            "framework-only lines in " + ReportText.Count(h.FrameworkProjects, "project") + ReportText.Change(report));
        Tile(body, ReportText.Fraction(h.ApplicationsDone, h.Applications), "applications with nothing left to port");
        Tile(body, h.Ready.ToString(CultureInfo.InvariantCulture), (h.Ready == 1 ? "project" : "projects") + " ready to port today");
        body.Append("</section>\n");
    }

    private static void BurnDown(StringBuilder body, ReportData report)
    {
        body.Append("<section>\n<h2>Burn-down</h2>\n");
        Legend(body);
        body.Append("<figure>\n").Append(Charts.BurnDown(report.Series)).Append("\n<figcaption>");
        body.Append(report.Series.Count == 1
            ? "Lines of code by framework class. One scan so far: the chart grows with each <code>offramp scan</code> whose ledger snapshot is committed."
            : "Lines of code by framework class at each scan; the line is framework-only code.");

        body.Append("</figcaption>\n</figure>\n</section>\n");
    }

    private static void Areas(StringBuilder body, ReportData report)
    {
        body.Append("<section>\n<h2>By area</h2>\n");
        Legend(body);
        body.Append("<figure>\n").Append(Charts.ByArea(report.Areas))
            .Append("\n<figcaption>Lines of code by framework class in each directory that holds project folders.</figcaption>\n</figure>\n</section>\n");
    }

    private static void Applications(StringBuilder body, ReportData report)
    {
        body.Append("<section>\n<h2>Applications</h2>\n");
        if (report.Applications.Count == 0)
        {
            body.Append("<p class=\"note\">No console, service, web, or desktop applications in the workspace.</p>\n</section>\n");
            return;
        }

        body.Append("<table>\n<thead><tr><th>Application</th><th>Kind</th><th>Status</th><th class=\"num\">Projects left</th>")
            .Append("<th class=\"num\">Lines left</th><th>Port next</th></tr></thead>\n<tbody>\n");
        foreach (var app in report.Applications)
        {
            var status = ReportText.Wire(app.Status);
            body.Append("<tr><td title=\"").Append(Encode(app.Project)).Append("\">").Append(Encode(app.Name)).Append("</td><td>")
                .Append(ReportText.Wire(app.Kind)).Append("</td><td><span class=\"status ").Append(status).Append("\">").Append(status).Append("</span></td>")
                .Append("<td class=\"num\">").Append(ReportText.Fraction(app.Remaining, app.Closure)).Append("</td><td class=\"num\">")
                .Append(app.RemainingLoc.ToString("N0", CultureInfo.InvariantCulture)).Append("</td><td>")
                .Append(string.Join(", ", app.Next.Select(n => "<code>" + Encode(n) + "</code>"))).Append("</td></tr>\n");
        }

        body.Append("</tbody>\n</table>\n<p class=\"note\">Projects left: framework-only projects among the application and everything it depends on.</p>\n</section>\n");
    }

    private static void Frontier(StringBuilder body, ReportData report)
    {
        body.Append("<section>\n<h2>Ready to port today</h2>\n");
        if (report.Frontier.Count == 0)
        {
            body.Append("<p class=\"note\">")
                .Append(report.Headline.FrameworkProjects == 0 ? "Nothing is framework-only any more." : "Every framework-only project waits on another; see the cycles in <code>offramp graph</code>.")
                .Append("</p>\n</section>\n");
            return;
        }

        body.Append("<p class=\"note\">Framework-only projects whose dependencies are all portable, the ones most depended on first.</p>\n")
            .Append("<table>\n<thead><tr><th>Project</th><th class=\"num\">Lines</th><th class=\"num\">Dependents</th></tr></thead>\n<tbody>\n");
        foreach (var project in report.Frontier)
        {
            body.Append("<tr><td><code>").Append(Encode(project.Project)).Append("</code></td><td class=\"num\">")
                .Append(project.Loc.ToString("N0", CultureInfo.InvariantCulture)).Append("</td><td class=\"num\">")
                .Append(project.Dependents.ToString(CultureInfo.InvariantCulture)).Append("</td></tr>\n");
        }

        body.Append("</tbody>\n</table>\n</section>\n");
    }

    private static void Tile(StringBuilder body, string value, string label) =>
        body.Append("<div class=\"tile\"><div class=\"value\">").Append(Encode(value)).Append("</div><div class=\"label\">").Append(Encode(label)).Append("</div></div>\n");

    private static void Legend(StringBuilder body)
    {
        body.Append("<ul class=\"legend\">");
        foreach (var name in ReportBuilder.Classes)
        {
            body.Append("<li><span class=\"swatch\" style=\"background:").Append(Charts.Color(name)).Append("\"></span>").Append(name).Append("</li>");
        }

        body.Append("</ul>\n");
    }

    private static string Encode(string value) => WebUtility.HtmlEncode(value);
}
